model_device: "cpu"
torch_cpu_threads: 1
lazy_store_folder: "./data"

servers:
  1435668295410782290:
    name: "Real Server"
    active: true
    bot_channel_id: 1441539591856197684
    student_role_id: 1435671205293064254
    classifier_confs:
      models:
        cats:
          model_path: "cats"
          auto_respond_channels: [1441539591856197684]
          manual_trigger_reaction: "🐱"
          confidence_thresholds: {HIGH: 0.68, MID: 0.4, LOW: 0.0}
          select_random_prob: 0.4  # Alternative is select the script used the least recently
          scripts:
            - { priority: 10, label:     "andy", confidence: "HIGH", text: "\"Oh wacky tobacky this is Andy!\" - Connor" }
            - { priority: 10, label:     "andy", confidence: "HIGH", text: "Andy! Go to sleep!" }
            - { priority: 10, label:     "andy", confidence: "HIGH", text: "Take your bets if Andy's leaving FRB before it's tomorrow" }
            - { priority: 10, label:     "bean", confidence: "HIGH", text: "Send bean pics" }
            - { priority: 10, label:     "bean", confidence: "HIGH", text: "Hey, when are you doing playdate?" }
            - { priority: 10, label:   "harvey", confidence: "HIGH", text: "Harvey! Outside of a couch! It's more likely than you think." }
            - { priority: 10, label:   "harvey", confidence: "HIGH", text: "Oh Harvey, please stop being a menace at night" }
            - { priority: 10, label:     "levi", confidence: "HIGH", text: "It's the perfect princess Laverne!" }
            - { priority: 10, label:   "merlin", confidence: "HIGH", text: "Watch your feet Merlin's here" }
            - { priority: 10, label:   "merlin", confidence: "HIGH", text: "STINKY!" }
            - { priority: 10, label:   "merlin", confidence: "HIGH", text: "Get put in air jail!" }
            - { priority: 10, label:   "merlin", confidence: "HIGH", text: "He demand the pank!" }
            - { priority: 10, label:  "wrigley", confidence: "HIGH", text: "I can hear Wrigley purring from here!" }
            - { priority: 10, label:  "wrigley", confidence: "HIGH", text: "Whoa, you got some big paws there Wrigley!" }
            - { priority:  0, label:      "ANY", confidence: "HIGH", text: "AWWWW it's {cats_label_1}!" }
            - { priority:  0, label:      "ANY", confidence:  "MID", text: "Could it be! Is it {cats_label_1}?! Or wait is it {cats_label_2}?" }
            - { priority:  0, label:      "ANY", confidence:  "LOW", text: "Who is this man? {cats_label_1}?" }
        emotions:
          model_path: "emotions"
          auto_respond_channels: [1441539591856197684]
          manual_trigger_reaction: "😄"
          confidence_thresholds: {HIGH: 0.68, MID: 0.4, LOW: 0.0}
          select_random_prob: 0.4  # Alternative is select the script used the least recently
          scripts:
            - { priority: 10, label:  "angy", confidence: "HIGH", text: "Oh? Somebody is angy!" }
            - { priority: 10, label: "needy", confidence: "HIGH", text: "Looks like someone needs attention!" }
            - { priority: 10, label:  "eepy", confidence: "HIGH", text: "Time for sleep (˘o˘ )"}
            - { priority: 10, label: "hungy", confidence: "HIGH", text: "FOOD! GIVE!"}
            - { priority: 10, label:  "andy", confidence: "HIGH", text: "Feelin a bit andy today."}
            - { priority:  0, label:   "ANY", confidence: "HIGH", text: "Whoof, that's {emotions_label_1}!"}
            - { priority:  0, label:   "ANY", confidence:  "MID", text: "Could it be! Is it {emotions_label_1}?! Or wait is it {emotions_label_2}?"}
            - { priority:  0, label:   "ANY", confidence:  "LOW", text: "Someone's feeling {emotions_label_1}? Or is it {emotions_label_2}?"}
    council_of_teds_confs:
      nay_vote_emoji: ":honse:"
      council_members:
        ted:
          internal_name: "Ted"
          ted_id: 1
          council_name: "The First True Ted"
          epithets: ["The Only"]
          words: "Unicus"
          user_id: 255516285985619970
          crest_emoji: ":unicus:"
        aidan:
          internal_name: "Aidan"
          ted_id: 2
          council_name: "The Second True Ted"
          epithets: ["The Botfather", "The Usurper"]
          words: "Dempseram"
          user_id: 728600387501686836
          crest_emoji: ":dempseram:"
        andy:
          internal_name: "Andy"
          ted_id: 3
          council_name: "The Third True Ted?"
          epithets: ["Him of the Lab"]
          words: "Fortasse"
          user_id: 1405215475688018002
          crest_emoji: ":fortasse:"
        jace:
          internal_name: "Jace"
          ted_id: 4
          council_name: "The Last True Ted"
          epithets: ["The Final"]
          words: "Terminus"
          user_id: 588908461149126656
          crest_emoji: ":terminus:"
    jail_confs:
      jail_emoji: "tojail"
      tomato_emoji: "🍅"
      to_jail_threshold: 3
      mega_jail_threshold: 5
      jail_length_ms: 86400000  # 24 hours in milliseconds
      jailed_role_id: 1469122341496688790
      on_jailed_scripts:
        - "Hark! {jailed_user} has been sent to the stocks for heinous speech!"
        - "Hah! Mock {jailed_user} thus! Forsooth, unto the stocks they hath been led!"
        - "Aha! Attend to the pillory, that thou mayest receive thy just chastisement!"
        - "Thou shalt be send to prisone, forsooth, for thine grievous trespasses!"
      mega_jail_scripts:
        - "The people have spoken. {jailed_user}'s name is forfeit. The first reply to this message will be their new name."
      humiliate_scripts:
        - "Silence {jailed_user}! I throw a tomato at thee!"
        - "Take a tomato unto thine head!"
        - "Halt thy prattling!"
        - "Quiete thy voice and be still."
        - "Hark ye, be ye mute as stone."
      assult_innocent_scripts:
        - "HALT {reacting_user}! You have tomatoed the innocent {attacked_user}! I will remember this!"
      already_in_jail_scripts:
        - "Alas! {jailed_user} is already in jail! How can they be double jailed?"
      release_scripts:
        - "Alright, {jailed_user}. You've served your time. Don't let it happen again."
      scot_free_scripts:
        - "What are you doing in the stocks {jailed_user}? You're free to go."
      forgotten_prisoner_scripts:
        - "You're not on the lists {jailed_user}. Well you must be here for a reason. Back in the stocks!"
      bean_coin_emoji: "BeanCoin"
      bribe_cost: 10
      max_coins_per_day: 2
      bribe_success_scripts:
        - "The honorable {botname} has decided that {jaileduser} is innocent of their crime and must be released immediately!"
        - "Huzzah! The coffers overflow! Coincidentally {jaileduser} walks free!"
        - "Ah! The bars doth found themselves open! {jaileduser} hath made haste!"
        - "What ho, a mighty persuasion! Take thou stealth as thou walkest forsooth!"
      bribe_failure_scripts:
        - "FOR SHAME! {jaileduser} has attempted to bribe your competent and faithful bot! Tomato them!"
        - "Did you think I could be bought so easily, {jaileduser}? Double the guard!"
        - "Thine coin doth not fill mine pocket enough!"
        - "How darest thou seek to purchase mine acceptance with a paltry sum!"
        - "Wouldest thou seek to corrupt me with coin? A curse upon thee, villain!"
    birthday_confs:
      birthdays_message_channel_id: 1435678059138121788
      birthdays_message_id: 1491511145511518318
      
      enable_holidays: true
      enable_on_this_day: true
    fat_cow_confs:
      reactions:
        no_fat_cow_emoji: "knife"
        low_fat_cow_threshold: 0.5
        low_fat_cow_emoji: "cow"
        medium_fat_cow_threshold: 1.0
        medium_fat_cow_emoji: "🇬,🇴,🅾️,🇩"
        high_fat_cow_threshold: 1.5
        high_fat_cow_emoji: "🇭,🇴,🇼,❓"
        very_high_fat_cow_emoji: "tojail"
